var cn = {
    Save: "保存",
    "Save all": "全部保存",
    Rename: "改名",
    Open: "打开",
    Edit: "编辑",
    Delete: "删除",
    Folder: "文件夹",
    "Add New": "新添加",
    Size: "大小",
    Date: "数据",
    "back to parent folder": "返回上级",
    Download: "下载",
    Type: "Type",
    Information: "信息",
    Files: "文件",
    Table: "表格",
    Cards: "卡片",
    Total: "总计",
    "Are you sure ?": "你确定要这样做 ?",
    Details: "详细",
    "Enter a new name": "输入新名称",
    Add: "添加",
    "Select something": "多选",
    "Download file": "下载文件",
    Preview: "预览",
    Refresh: "刷新",
    "Are you sure you want to exit without saving?": "您确定要退出而不保存吗?",
    "Save before closing?": "关闭前保存？",
    Copy: "复制",
    Cut: "剪切",
    Paste: "粘贴",
    "Deleting...": "删除中...",
    "Copying...": "复制中...",
    "Moving...": "移动中...",
    Folders: "文件夹",
    "Search results": "搜索结果",
    "Search results in": "搜索结果",
    "Search files and folders": "搜索文件和文件夹",
    "Add new file": "新建文件",
    "Add new folder": "新建文件夹",
    "Upload file": "上传文件",
    folder: "文件夹",
    file: "文件",
    archive: "档案",
    audio: "音频",
    image: "图片",
    video: "视频",
    code: "代码",
    document: "文档",
    of: "of",
    used: "used",
    "Open item location": "打开项目位置",
    "Are you sure you want to delete": "你确定要删除？",
    "these items:": "全部项目:",
    "this item:": "项目:",
    "Delete files": "删除文件",
    and: "和",
    "more file(s)": "移动多个文件",
    "Close the editor": "关闭编辑",
    "Close this file": "关闭文件",
    "Owner": "所有者",
    "Permissions": "权限",
    "Change Permissions": "更改权限",
    "Set": "设置",
    "Extract": "提取",
    "Extract directory": "提取目录",
    "Extracting...": "提取中...",
    "Compress": "压缩",
    "Compressing...": "压缩中...",
};